<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /* @var $block \Magento\Catalog\Block\Product\View\AbstractView */?>
<?php $_product = $block->getProduct() ?>

<?php
$is_pre_order = $_product->getPreOrder();
if($is_pre_order) { ?>
	<div class="stock available" title="<?php /* @escapeNotVerified */ echo __('Availability') ?>">
		<?php /* @escapeNotVerified */ echo __('Availability') ?>: <span><?php /* @escapeNotVerified */ echo __('Future Release') ?></span>
	</div>
<?php } else if ($block->displayProductStockStatus()) {
	if ($_product->isAvailable()): ?>
	<div class="stock available" title="<?php /* @escapeNotVerified */ echo __('Availability') ?>">
		<?php /* @escapeNotVerified */ echo __('Availability') ?>: <span><?php /* @escapeNotVerified */ echo __('In stock') ?></span>
	</div>
<?php else: ?>
	<div class="stock unavailable" title="<?php /* @escapeNotVerified */ echo __('Availability') ?>">
		<?php /* @escapeNotVerified */ echo __('Availability') ?>: <span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span>
	</div>
<?php endif;
}
?>